import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@ant-design/v5-patch-for-react-19';
import "./globals.css";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import LayoutClient from "@/LayoutClient";
import StoreProvider from "@/lib/StoreProvider";

export const metadata: Metadata = {
    title: "AOV",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body suppressHydrationWarning
                className={`antialiased`}
            >
                <StoreProvider>
                    <LayoutClient>
                        {children}
                    </LayoutClient>
                </StoreProvider>
            </body>
        </html>
    );
}
