import { Soldier } from "./Soldier";

const defaultSoldiers: Record<string, Soldier> = {
    s1: {
        id: 's1',
        type: 'melee',
        hp: 300,
        maxHp: 300,
        position: { x: 0, y: 0 },
        speed: 120,
        attackDamage: 25,
        attackRange: 1.5,
        attackSpeed: 1,
        armor: 10,
        magicResist: 5,
        team: 'ally',
        isAlive: true,
    },
    s2: {
        id: 's2',
        type: 'melee',
        hp: 300,
        maxHp: 300,
        position: { x: 10, y: 0 },
        speed: 120,
        attackDamage: 25,
        attackRange: 1.5,
        attackSpeed: 1,
        armor: 10,
        magicResist: 5,
        team: 'ally',
        isAlive: true,
    },
    s3: {
        id: 's3',
        type: 'ranged',
        hp: 250,
        maxHp: 250,
        position: { x: 20, y: 0 },
        speed: 100,
        attackDamage: 20,
        attackRange: 4,
        attackSpeed: 1.2,
        armor: 8,
        magicResist: 6,
        team: 'ally',
        isAlive: true,
    },
    s4: {
        id: 's4',
        type: 'melee',
        hp: 300,
        maxHp: 300,
        position: { x: 30, y: 0 },
        speed: 120,
        attackDamage: 25,
        attackRange: 1.5,
        attackSpeed: 1,
        armor: 10,
        magicResist: 5,
        team: 'enemy',
        isAlive: true,
    },
    s5: {
        id: 's5',
        type: 'ranged',
        hp: 250,
        maxHp: 250,
        position: { x: 40, y: 0 },
        speed: 100,
        attackDamage: 20,
        attackRange: 4,
        attackSpeed: 1.2,
        armor: 8,
        magicResist: 6,
        team: 'enemy',
        isAlive: true,
    },
};
export default defaultSoldiers
